ProTwo/AppTwo/urls.py
from django.urls import path
from . import views
app_name = 'AppTwo'
urlpatterns = [
    path('users/',views.users,name='users'),
    path('register/',views.register,name='register'),
    path('help/',views.help, name='help'),
    path('user_login/',views.user_login, name='user_login')
]

ProTwo/ProTwo/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from AppTwo import views

urlpatterns = [
    path('AppTwo/', include('AppTwo.urls')),
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('logout/',views.user_logout, name='logout')
    # path('help/',views.help, name='help')
    # re_path(r'help/', include('AppTwo.urls')),
    # path('staticimage',views.image, name="image"),



]

ProTwo/AppTwo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)


    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username











# class User(models.Model):
#     FirstName = models.CharField(max_length=200)
#     LastName = models.CharField(max_length=200)
#     Email = models.EmailField(max_length=254)
#
#     def __str__(self):
#         return self.FirstName + " " + self.LastName

# class UserFormModel(models.Model):
#     FirstName = models.CharField(max_length = 200)
#     LastName = models.CharField(max_length=200)
#     Email = models.EmailField(max_length=254)
#
#     # class Meta:
#     #     ordering = ['name']
#
#     def __str__(self):
#         return f"Form by {self.name}"

ProTwo/AppTwo/forms.py
from .models import UserProfile
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User

class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password') #['firstname', 'lastname', 'email']

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)








# class Form(ModelForm):
#     # firstname = forms.CharField(label='')
#     # lastname = forms.CharField(label='')
#     # email = forms.EmailField(label='')
#
#     class Meta:
#         model = User
#         fields = '__all__' #['firstname', 'lastname', 'email']
#
#     # firstname = forms.CharField()
#     # lastname = forms.CharField()
#     # email = forms.EmailField()

ProTwo/AppTwo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from .models import UserProfile
from django.contrib.auth.models import User
from .forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'AppTwo/index.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect('index')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return redirect('index')
            else:
                return HttpResponse("Your account is not active")

        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied")

    else:
        return render(request, 'AppTwo/login.html')

def help(request):
    dic = {
    'content':"help page"
    }
    return render(request,'AppTwo/help.html',dic)

def image(request):
    return render(request,'static_image.html')

def users(request):
    users = User.objects.all()
    # users = User.objects.all()
    # users = {i.objects.values() for i in users}
    # print(users)
    # serial_no = [i for i in range(1,len(users)+1)]
    return render(request, 'AppTwo/user.html',context={'users':users})

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()

            user.set_password(user.password)

            user.save()

            profile = profile_form.save(commit = False)

            profile.user = user

            if 'profile_pic' in request.FILES:
                print('found it')

                profile.profile_pic = request.FILES['profile_pic']

                profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm(request.GET)
        profile_form = UserProfileForm(request.GET)

    return render(request,'AppTwo/register.html',
                        {'user_form':user_form,
                        'profile_form':profile_form,
                        'registered':registered
                        })















# def userform(request):
#     form = Form(request.GET)
#     if request.method == 'POST':
#         form = Form(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponse('Your details has been stored')

    # else:
    #     form = Form(request.GET)
    #     context = {
    #         'form':form,
    #     }
    # # # form = forms.userForm(request.POST)
    # return render(request, 'AppTwo/form_page.html',{'form':form})

ProTwo/templates/AppTwo/base_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
      {% endblock title %}
    </title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
{% block css %}
{% endblock css %}
  </head>
  <body>

    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">AppTwo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'AppTwo:users' %}">Users</a></li>
        <li><a href="{% url 'AppTwo:register' %}">Register</a></li>
        <li><a href="{% url 'AppTwo:help' %}">Help</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}" target="_blank">Admin</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'AppTwo:user_login' %}">Login</a></li>
        {% endif %}
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    {% block body %}
    {% endblock body %}
  </body>
</html>

ProTwo/templates/AppTwo/help.html
<!DOCTYPE html>

{% extends 'AppTwo/base_template.html' %}
{% block title %}
Help!
{% endblock title %}
{% block body %}
<div class="container">


  <div class="jumbotron">
    <h1>Welcome to {{ content|title }} </h1>
  </div>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p>Copyright (c) 2018 Copyright Holder All Rights Reserved.</p>
</div>
{% endblock body %}

ProTwo/templates/AppTwo/index.html
<!DOCTYPE html>
{% extends 'AppTwo/base_template.html' %}
{% load static %}
{% block title %}
Index
{% endblock title %}
{% block css %}
<style>
img {
  display: block;
  margin: 0px auto;
  height:"250px";
  width:"300px";
}
</style>
{% endblock css %}
{% block body %}
    <div class="container">
      <div class="jumbotron">
        <h1>Welcome To HomePage</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <img src="{% static 'images/sample.jpg' %}" alt="image is not showing">
      </div>
    </div>
{% endblock body %}

ProTwo/templates/AppTwo/login.html
{% extends 'AppTwo/base_template.html' %}
{% block title %}Login{% endblock title %}
{% block body %}
<div class="container">
  <div class="jumbotron">
    <h1>Login</h1>
  </div>
  <form action="{% url 'AppTwo:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Username"><br><br>

    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Password"><br><br>

    <input type="submit" name="" value="Login" class="btn btn-primary">
  </form>
</div>
{% endblock body %}

ProTwo/templates/AppTwo/register.html
{% extends 'AppTwo/base_template.html' %}
{% block title %}
Register
{% endblock title %}
  {% block css %}
    <style media="screen">
      /* .formdiv {
        border:1px solid black;
      } */
      form {
        padding-left:20px;
      }
    </style>

    {% endblock css%}
{% block body %}

    <div class="container">
      <div class="jumbotron">
        {% if registered %}
          <h1>Thank you for Registering!</h1>
          <p>Goto Login Page  to Log into website</p>
        {% else %}
          <h1>Register Form</h1>
          <p>Fill Out The Details To Register</p>

            </div>
          <form enctype="multipart/form-data" method="post">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" value="Register" class="btn btn-primary">
        </form>

        {% endif %}
  </div>
{% endblock body %}

ProTwo/templates/AppTwo/user.html
<!DOCTYPE html>
{% extends 'AppTwo/base_template.html' %}
{% block title %}
USERS
{% endblock title %}

{% block css %}

  <style media="screen">
    table {
      margin-top:50px;
    }
    td, th {
      text-align:center;
    }
  </style>

  {% endblock css %}

  {% block body %}
    <div class="container">
      <div class="jumbotron">
        <h1>Here are your users:</h1>
        </div>

    <table class="table table-striped table-bordered">
      <tr>
        <thead>
          <th>FirstName</th>
          <th>LastName</th>
          <th>Email</th>
        </thead>
      </tr>
      {% for entry in users %}
        {% if entry.is_staff == False %}
          <tr>
            <!-- <td>{{snum}}</td> -->
            <td>{{entry.first_name}}</td>
            <td>{{entry.last_name}}</td>
            <td>{{entry.email}}</td>
          </tr>
        {% endif %}
      {% endfor %}
    </table>
<!-- </div> -->
</div>
  {% endblock body %}

ProTwo/templates/static_image.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <img src="{% static 'images/sample.jpg' %}" alt="image is not showing">

  </body>
</html>